// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CancelToken`, `TransportErrorCode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `canceled`, `check`, `conflict`, `internal`, `invalid_argument`, `is_cancelled`, `not_found`, `timeout`, `token`

/// 工厂: Dart 侧 `await newCancelHandle()` 拿到 `RustOpaque<CancelHandle>`。
Future<CancelHandle> newCancelHandle() =>
    RustLib.instance.api.crateApiTransportCommonNewCancelHandle();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CancelHandle>>
abstract class CancelHandle implements RustOpaqueInterface {
  /// Dart 侧调用。幂等。
  Future<void> cancel();

  static Future<CancelHandle> default_() =>
      RustLib.instance.api.crateApiTransportCommonCancelHandleDefault();

  bool isCancelled();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<CancelHandle> newInstance() =>
      RustLib.instance.api.crateApiTransportCommonCancelHandleNew();
}

/// 任务进度。`fraction` ∈ [0.0, 1.0]; `stage` 是人类可读阶段名。
class ProgressDto {
  final double fraction;
  final String stage;
  final String? message;

  const ProgressDto({
    required this.fraction,
    required this.stage,
    this.message,
  });

  @override
  int get hashCode => fraction.hashCode ^ stage.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressDto &&
          runtimeType == other.runtimeType &&
          fraction == other.fraction &&
          stage == other.stage &&
          message == other.message;
}

/// 跨边界的标准化错误。Dart 侧据 `code` 字段映射到 UI 文案 / 重试策略。
///
/// 用扁平 struct + `code` 字符串 (而非带数据的 sum-type enum), 避免触发 FRB
/// 要求 `freezed` 依赖。`code` 枚举值定义见 `TransportErrorCode` 常量。
///
/// 业务系统应**包装**而不是**透传** `anyhow::Error`: 任何 Rust 内部错误
/// 在抵达 FFI 边界前都应转成此结构。
class TransportError implements FrbException {
  /// 错误码: `invalid_argument` / `not_found` / `conflict` / `canceled` / `timeout` / `internal`。
  final String code;

  /// 人类可读消息; 不含 PII、不含堆栈。
  final String message;

  /// 仅 `timeout` 用; 其余为 0。
  final BigInt elapsedMs;

  const TransportError({
    required this.code,
    required this.message,
    required this.elapsedMs,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          elapsedMs == other.elapsedMs;
}
