// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `panic_msg`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `catch_panic_async`, `catch_panic_sync`

/// 演示入口: Dart 调它会看到一个 `TransportError::internal("panic: ...")` 而非进程崩溃。
Future<String> transportSamplePanicDemo({required bool shouldPanic}) => RustLib
    .instance
    .api
    .crateApiTransportPatternTPanicSafetyTransportSamplePanicDemo(
      shouldPanic: shouldPanic,
    );
