// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `wait_cancel`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// fan-out: 并行执行 N 个子任务, 任一失败则取消其余, 返回所有成功结果 + 第一个失败。
///
/// `inputs` 限 32 个以内, 防止意外提交大批任务。
Future<TransportSampleFanoutResult> transportSampleFanout({
  required List<String> inputs,
  required BigInt perTaskMs,
  required CancelHandle cancel,
}) => RustLib.instance.api
    .crateApiTransportPatternUStructuredTransportSampleFanout(
      inputs: inputs,
      perTaskMs: perTaskMs,
      cancel: cancel,
    );

/// 取第一个成功者; 其余子任务 (在 select! 中) 因 drop 而自然停止。
Future<String> transportSampleRace({
  required List<String> candidates,
  required BigInt perTaskMs,
}) =>
    RustLib.instance.api.crateApiTransportPatternUStructuredTransportSampleRace(
      candidates: candidates,
      perTaskMs: perTaskMs,
    );

class TransportSampleFanoutResult {
  final int completed;
  final List<String> partial;

  const TransportSampleFanoutResult({
    required this.completed,
    required this.partial,
  });

  @override
  int get hashCode => completed.hashCode ^ partial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSampleFanoutResult &&
          runtimeType == other.runtimeType &&
          completed == other.completed &&
          partial == other.partial;
}
