// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bus`, `now_ms`, `snapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Rust 内任意地方调用 (含其它 pattern 文件)。Dart 端不需要直接调用此函数。
Future<void> publishEvent({required String topic, required String payload}) =>
    RustLib.instance.api.crateApiTransportPatternIEventBusPublishEvent(
      topic: topic,
      payload: payload,
    );

/// Dart 订阅。每次调用新建一个独立的接收端 (broadcast 语义)。
///
/// `include_snapshot=true` 时, 先回放 snapshot (每个 topic 最新一条), 再衔接实时流。
Stream<TransportSampleEventDto> subscribeEvents({
  required bool includeSnapshot,
}) => RustLib.instance.api.crateApiTransportPatternIEventBusSubscribeEvents(
  includeSnapshot: includeSnapshot,
);

/// 清空快照。仅供测试 / 维护; 不影响订阅者。
Future<int> transportSampleEventBusClearSnapshot() => RustLib.instance.api
    .crateApiTransportPatternIEventBusTransportSampleEventBusClearSnapshot();

class TransportSampleEventDto {
  final String topic;
  final String payload;
  final PlatformInt64 timestampMs;

  const TransportSampleEventDto({
    required this.topic,
    required this.payload,
    required this.timestampMs,
  });

  @override
  int get hashCode => topic.hashCode ^ payload.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSampleEventDto &&
          runtimeType == other.runtimeType &&
          topic == other.topic &&
          payload == other.payload &&
          timestampMs == other.timestampMs;
}
