// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 示例: 异步执行一段业务用例; 这里以 `tokio::time::sleep` 模拟 IO。
Future<String> transportSampleCompute({required String input}) => RustLib
    .instance
    .api
    .crateApiTransportPatternBAsyncTransportSampleCompute(input: input);

/// 演示带超时的用例式 API。生产建议把超时作显式参数, 而不是隐式默认值。
Future<String> transportSampleWithTimeout({
  required String input,
  required BigInt timeoutMs,
}) => RustLib.instance.api
    .crateApiTransportPatternBAsyncTransportSampleWithTimeout(
      input: input,
      timeoutMs: timeoutMs,
    );
