// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 分阶段长任务: 每步检查取消位; 取消时返回 `canceled` 且包含已完成步数。
Future<String> transportSampleSlowJob({
  required String input,
  required int steps,
  required BigInt stepMs,
  required CancelHandle cancel,
}) =>
    RustLib.instance.api.crateApiTransportPatternDCancelTransportSampleSlowJob(
      input: input,
      steps: steps,
      stepMs: stepMs,
      cancel: cancel,
    );
