// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 单次返回大缓冲: Dart 侧拿到 `Uint8List`。
Future<Uint8List> transportSampleBigBytes({required BigInt size}) => RustLib
    .instance
    .api
    .crateApiTransportPatternGBytesTransportSampleBigBytes(size: size);

/// 把一段 payload 切块推给 Dart。
Stream<Uint8List> transportSampleChunkStream({
  required BigInt totalSize,
  required BigInt chunkSize,
}) => RustLib.instance.api
    .crateApiTransportPatternGBytesTransportSampleChunkStream(
      totalSize: totalSize,
      chunkSize: chunkSize,
    );
