// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_or_init`, `registry`

/// 配置一个命名 Semaphore 的权重。仅在该 key 首次创建时生效;
/// 已经存在的 Semaphore 不会被替换 (防止运行中改容量导致越权)。
Future<bool> transportSampleConfigureSemaphore({
  required String name,
  required int permits,
}) => RustLib.instance.api
    .crateApiTransportPatternNSemaphoreTransportSampleConfigureSemaphore(
      name: name,
      permits: permits,
    );

/// 限流地执行一段昂贵操作。
///
/// - `name`: 选用哪个命名池 (业务隔离)。空字符串 = 默认池。
/// - `acquire_timeout_ms`: 若 >0, 等待时间超过此值返回 `timeout`; 否则一直等。
Future<String> transportSampleThrottledOp({
  required String name,
  required BigInt acquireTimeoutMs,
  required String input,
}) => RustLib.instance.api
    .crateApiTransportPatternNSemaphoreTransportSampleThrottledOp(
      name: name,
      acquireTimeoutMs: acquireTimeoutMs,
      input: input,
    );

/// 查询某个 Semaphore 的当前可用槽位。便于观测/告警。
Future<int> transportSampleSemaphoreAvailable({required String name}) => RustLib
    .instance
    .api
    .crateApiTransportPatternNSemaphoreTransportSampleSemaphoreAvailable(
      name: name,
    );
