// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex_lower`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 消费一个 Dart 写到磁盘上的文件。
///
/// - `expected_sha256`: 若提供, 与实际内容比对失败时返回 `conflict`。
/// - `delete_after`: 处理成功后是否删除原文件。删除失败不视为错误 (回执的 `deleted` 字段会为 false)。
Future<TransportSampleFileReceiptDto> transportSampleConsumeFile({
  required String path,
  String? expectedSha256,
  required bool deleteAfter,
}) => RustLib.instance.api
    .crateApiTransportPatternSFileHandoffTransportSampleConsumeFile(
      path: path,
      expectedSha256: expectedSha256,
      deleteAfter: deleteAfter,
    );

/// 文件处理回执。
///
/// `verified` 只在调用方提供了 `expected_sha256` 时有意义:
/// - `Some(true)`: 内容哈希与预期一致。
/// - `Some(false)`: 不一致 (此时函数会返回 `Err(conflict)`, 调用方应不会看到此值)。
/// - `None`: 未要求校验。
class TransportSampleFileReceiptDto {
  final BigInt bytesRead;
  final String sha256Hex;
  final bool? verified;
  final bool deleted;

  const TransportSampleFileReceiptDto({
    required this.bytesRead,
    required this.sha256Hex,
    this.verified,
    required this.deleted,
  });

  @override
  int get hashCode =>
      bytesRead.hashCode ^
      sha256Hex.hashCode ^
      verified.hashCode ^
      deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSampleFileReceiptDto &&
          runtimeType == other.runtimeType &&
          bytesRead == other.bytesRead &&
          sha256Hex == other.sha256Hex &&
          verified == other.verified &&
          deleted == other.deleted;
}
