// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FixedClock`, `SystemClock`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `freshness_ms`, `now_ms`, `now_ms`

/// FRB 暴露的版本: 默认用 SystemClock。生产代码引用此入口。
Future<PlatformInt64> transportSampleFreshnessMs({
  required PlatformInt64 createdAtMs,
}) => RustLib.instance.api
    .crateApiTransportPatternQMockTransportSampleFreshnessMs(
      createdAtMs: createdAtMs,
    );

abstract class TransportSampleClock {
  Future<PlatformInt64> nowMs();
}
