// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 示例: 两个数的加法。生产中应是更有意义的纯计算（哈希、几何变换等）。
PlatformInt64 transportSampleAdd({
  required PlatformInt64 a,
  required PlatformInt64 b,
}) => RustLib.instance.api.crateApiTransportPatternASyncTransportSampleAdd(
  a: a,
  b: b,
);

/// 带校验的同步函数: 演示如何返回 `Result<T, TransportError>`。
///
/// FRB 会把 `Result` 转成 Dart 侧的抛出异常。
double transportSampleClampPercent({required double value}) => RustLib
    .instance
    .api
    .crateApiTransportPatternASyncTransportSampleClampPercent(value: value);
