// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Echo: Dart 侧把 `jsonEncode(obj)` 传入, Rust 加 trace 字段后回传。
///
/// 演示"不解码也能加工"的边界处理。生产里可换成"加签名 / 加包裹元数据"。
Future<String> transportSampleJsonPassthrough({required String payloadJson}) =>
    RustLib.instance.api
        .crateApiTransportPatternRJsonTransportSampleJsonPassthrough(
          payloadJson: payloadJson,
        );
