// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ProgressDto> transportSampleProgressJob({
  required int steps,
  required BigInt stepDurationMs,
  required CancelHandle cancel,
}) => RustLib.instance.api
    .crateApiTransportPatternEProgressTransportSampleProgressJob(
      steps: steps,
      stepDurationMs: stepDurationMs,
      cancel: cancel,
    );
