// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache`, `get`, `new`, `put`, `with_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CacheEntry`, `IdempotencyCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 接收一条"具有副作用"的请求; 相同 `idempotency_key` 在 TTL 内只执行一次。
Future<TransportSampleReceiptDto> transportSampleApplyOnce({
  required String idempotencyKey,
  required String payload,
}) => RustLib.instance.api
    .crateApiTransportPatternLIdempotentTransportSampleApplyOnce(
      idempotencyKey: idempotencyKey,
      payload: payload,
    );

/// 手动清理 (用于测试或维护)。返回清理前的条数。
Future<int> transportSampleIdempotencyCacheClear() => RustLib.instance.api
    .crateApiTransportPatternLIdempotentTransportSampleIdempotencyCacheClear();

class TransportSampleReceiptDto {
  final String key;
  final String result;
  final bool deduped;

  const TransportSampleReceiptDto({
    required this.key,
    required this.result,
    required this.deduped,
  });

  @override
  int get hashCode => key.hashCode ^ result.hashCode ^ deduped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSampleReceiptDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          result == other.result &&
          deduped == other.deduped;
}
