// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `now_ms`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 每 `interval_ms` 毫秒推送一个 tick, 共 `count` 个。
///
/// `interval_ms = 0` 表示尽可能快地推送 (会让出调度避免饥饿)。
Stream<TransportSampleTickDto> transportSampleTicks({
  required BigInt intervalMs,
  required BigInt count,
}) => RustLib.instance.api.crateApiTransportPatternCStreamTransportSampleTicks(
  intervalMs: intervalMs,
  count: count,
);

class TransportSampleTickDto {
  final BigInt seq;
  final PlatformInt64 timestampMs;

  const TransportSampleTickDto({required this.seq, required this.timestampMs});

  @override
  int get hashCode => seq.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSampleTickDto &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          timestampMs == other.timestampMs;
}
