// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionState`

/// 顶层工厂函数, 避免依赖 FRB 对 `impl` 静态方法的解析。
Future<TransportSampleSession> transportSampleOpenSession({
  required PlatformInt64 initial,
}) => RustLib.instance.api
    .crateApiTransportPatternFOpaqueTransportSampleOpenSession(
      initial: initial,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransportSampleSession>>
abstract class TransportSampleSession implements RustOpaqueInterface {
  /// 显式释放业务资源 (此处只是设标志)。Dart 侧 `RustOpaque` Drop 时也会回收内存。
  Future<void> dispose();

  Future<void> increment({required PlatformInt64 by});

  /// 工厂入口: Dart 侧 `await transportSampleOpenSession(initial: 0)`。
  static Future<TransportSampleSession> open({
    required PlatformInt64 initial,
  }) => RustLib.instance.api
      .crateApiTransportPatternFOpaqueTransportSampleSessionOpen(
        initial: initial,
      );

  Future<PlatformInt64> snapshot();
}
