// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReplInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<TransportSampleRepl> transportSampleOpenRepl() => RustLib.instance.api
    .crateApiTransportPatternHDuplexTransportSampleOpenRepl();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransportSampleRepl>>
abstract class TransportSampleRepl implements RustOpaqueInterface {
  /// 第一步: Dart 订阅事件流, 把 sink 注册到句柄上。重复 bind 返回 `conflict`。
  Stream<TransportSampleReplEvent> bindEvents();

  /// 显式关闭。后续 `submit` 返回 `conflict`; 幂等。
  Future<void> close();

  static Future<TransportSampleRepl> default_() => RustLib.instance.api
      .crateApiTransportPatternHDuplexTransportSampleReplDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TransportSampleRepl> newInstance() => RustLib.instance.api
      .crateApiTransportPatternHDuplexTransportSampleReplNew();

  /// 第二步: Dart 发命令; Rust 回 echo 事件。
  /// 未 bind 即 submit → `conflict`; sink 已关闭 → `conflict`。
  Future<void> submit({required String command});
}

class TransportSampleReplEvent {
  final String echoOf;
  final BigInt seq;

  const TransportSampleReplEvent({required this.echoOf, required this.seq});

  @override
  int get hashCode => echoOf.hashCode ^ seq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSampleReplEvent &&
          runtimeType == other.runtimeType &&
          echoOf == other.echoOf &&
          seq == other.seq;
}
