// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cell`, `now_ms`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RuntimeCell`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Dart 端显式调; 用于 hot-restart 或测试间隔离。
/// 这里只重置标志位; 真实业务应在此 flush 数据 / 关闭事件总线 / 关闭文件句柄。
Future<void> transportShutdown() =>
    RustLib.instance.api.crateApiTransportPatternPSingletonTransportShutdown();

TransportRuntimeInfo transportRuntimeInfo() => RustLib.instance.api
    .crateApiTransportPatternPSingletonTransportRuntimeInfo();

PlatformInt64 transportRuntimeStartedAtMs() => RustLib.instance.api
    .crateApiTransportPatternPSingletonTransportRuntimeStartedAtMs();

String transportRuntimeVersion() => RustLib.instance.api
    .crateApiTransportPatternPSingletonTransportRuntimeVersion();

class TransportRuntimeInfo {
  final PlatformInt64 startedAtMs;
  final String version;
  final bool running;

  const TransportRuntimeInfo({
    required this.startedAtMs,
    required this.version,
    required this.running,
  });

  @override
  int get hashCode =>
      startedAtMs.hashCode ^ version.hashCode ^ running.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportRuntimeInfo &&
          runtimeType == other.runtimeType &&
          startedAtMs == other.startedAtMs &&
          version == other.version &&
          running == other.running;
}
