// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 让 Dart 提供一个键值查询函数; Rust 用它解决"密钥/配置"问题。
///
/// `per_key_timeout_ms` 防止单个回调阻塞整个批处理。
Future<List<String?>> transportSampleWithKvProvider({
  required List<String> keys,
  required BigInt perKeyTimeoutMs,
  required FutureOr<String?> Function(String) get_,
}) => RustLib.instance.api
    .crateApiTransportPatternMCallbackTransportSampleWithKvProvider(
      keys: keys,
      perKeyTimeoutMs: perKeyTimeoutMs,
      get_: get_,
    );

/// 单次确认 (yes/no) 弹窗回调示例。Dart 侧实现 UI 对话框, Rust 业务等待结果。
Future<bool> transportSampleWithConfirm({
  required String prompt,
  required BigInt timeoutMs,
  required FutureOr<bool> Function(String) confirm,
}) => RustLib.instance.api
    .crateApiTransportPatternMCallbackTransportSampleWithConfirm(
      prompt: prompt,
      timeoutMs: timeoutMs,
      confirm: confirm,
    );
