// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `validate_id_like`, `validate_locale`, `validate_trace_parent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `check_deadline`, `deadline`, `minimal`, `validate`

/// 演示入口: 任意业务调用都可以照抄这个签名 (meta 作可选第一参数)。
///
/// 行为:
/// 1. 校验 meta。
/// 2. 如 `budget_ms` 已耗尽, 立刻 `timeout`。
/// 3. 模拟 `work_ms` 的工作; 期间每 10ms 检查 deadline。
/// 4. 返回回执, 含剩余预算。
Future<TransportSampleMetaReceiptDto> transportSampleWithMeta({
  required TransportRequestMeta meta,
  required String payload,
  required BigInt workMs,
}) => RustLib.instance.api
    .crateApiTransportPatternVRequestMetaTransportSampleWithMeta(
      meta: meta,
      payload: payload,
      workMs: workMs,
    );

/// 独立校验入口: Dart 侧 unit-test 用。生产业务**不需要**直接调它,
/// 因为 `transport_sample_with_meta` 已内置 validate。
Future<void> transportSampleValidateMeta({
  required TransportRequestMeta meta,
}) => RustLib.instance.api
    .crateApiTransportPatternVRequestMetaTransportSampleValidateMeta(
      meta: meta,
    );

/// 请求横切元数据。其他 pattern 可作可选第一参数接受。
class TransportRequestMeta {
  final String requestId;
  final String? idempotencyKey;
  final BigInt? budgetMs;
  final String? traceParent;
  final String? locale;
  final int attempt;
  final String? source;

  const TransportRequestMeta({
    required this.requestId,
    this.idempotencyKey,
    this.budgetMs,
    this.traceParent,
    this.locale,
    required this.attempt,
    this.source,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      idempotencyKey.hashCode ^
      budgetMs.hashCode ^
      traceParent.hashCode ^
      locale.hashCode ^
      attempt.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportRequestMeta &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          idempotencyKey == other.idempotencyKey &&
          budgetMs == other.budgetMs &&
          traceParent == other.traceParent &&
          locale == other.locale &&
          attempt == other.attempt &&
          source == other.source;
}

/// 调用回执: 演示 meta 的端到端语义 (校验 → 接收 → 回显)。
class TransportSampleMetaReceiptDto {
  final String requestId;
  final int attempt;
  final BigInt elapsedMs;
  final BigInt? budgetRemainingMs;
  final String? localeApplied;

  /// 服务端处理 input 的回显; 真实业务里这里是结果 DTO。
  final String echoedPayload;

  const TransportSampleMetaReceiptDto({
    required this.requestId,
    required this.attempt,
    required this.elapsedMs,
    this.budgetRemainingMs,
    this.localeApplied,
    required this.echoedPayload,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      attempt.hashCode ^
      elapsedMs.hashCode ^
      budgetRemainingMs.hashCode ^
      localeApplied.hashCode ^
      echoedPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSampleMetaReceiptDto &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          attempt == other.attempt &&
          elapsedMs == other.elapsedMs &&
          budgetRemainingMs == other.budgetRemainingMs &&
          localeApplied == other.localeApplied &&
          echoedPayload == other.echoedPayload;
}
