// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 演示分页: 实际项目把 cursor 解码为「上次最后一项的 (created_at, id)」二元组。
Future<TransportSamplePage> transportSampleListPage({
  String? cursor,
  required int limit,
}) => RustLib.instance.api
    .crateApiTransportPatternKPaginationTransportSampleListPage(
      cursor: cursor,
      limit: limit,
    );

class TransportSamplePage {
  final List<String> ids;
  final List<String> titles;
  final Int64List createdAtMs;
  final String? nextCursor;

  const TransportSamplePage({
    required this.ids,
    required this.titles,
    required this.createdAtMs,
    this.nextCursor,
  });

  @override
  int get hashCode =>
      ids.hashCode ^
      titles.hashCode ^
      createdAtMs.hashCode ^
      nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSamplePage &&
          runtimeType == other.runtimeType &&
          ids == other.ids &&
          titles == other.titles &&
          createdAtMs == other.createdAtMs &&
          nextCursor == other.nextCursor;
}
