// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dto.dart';
import 'api/fade.dart';
import 'api/recovery.dart';
import 'api/view.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1416312812;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_fragments',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  HomeViewDto crateApiViewBuildHomeView({
    required List<FragmentDto> fragments,
    required List<RecoveryDto> recoveries,
    required PlatformInt64 nowMs,
  });

  double crateApiFadeFadeLevel({
    required FragmentDto fragment,
    required List<RecoveryDto> recoveries,
    required PlatformInt64 nowMs,
  });

  double crateApiFadeGrowthScore({
    required List<FragmentDto> fragments,
    required List<RecoveryDto> recoveries,
    required PlatformInt64 nowMs,
  });

  Future<void> crateApiSimpleInitApp();

  RecordRecoveryOutcomeDto crateApiRecoveryRecordRecovery({
    required RecoveryDto recovery,
    required List<FragmentDto> relatedFragments,
  });

  int crateApiDtoSupportedFragmentSchemaVersion();

  int crateApiDtoSupportedRecoverySchemaVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  HomeViewDto crateApiViewBuildHomeView({
    required List<FragmentDto> fragments,
    required List<RecoveryDto> recoveries,
    required PlatformInt64 nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_fragment_dto(fragments, serializer);
          sse_encode_list_recovery_dto(recoveries, serializer);
          sse_encode_i_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_view_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiViewBuildHomeViewConstMeta,
        argValues: [fragments, recoveries, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiViewBuildHomeViewConstMeta => const TaskConstMeta(
    debugName: "build_home_view",
    argNames: ["fragments", "recoveries", "nowMs"],
  );

  @override
  double crateApiFadeFadeLevel({
    required FragmentDto fragment,
    required List<RecoveryDto> recoveries,
    required PlatformInt64 nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_fragment_dto(fragment, serializer);
          sse_encode_list_recovery_dto(recoveries, serializer);
          sse_encode_i_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFadeFadeLevelConstMeta,
        argValues: [fragment, recoveries, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFadeFadeLevelConstMeta => const TaskConstMeta(
    debugName: "fade_level",
    argNames: ["fragment", "recoveries", "nowMs"],
  );

  @override
  double crateApiFadeGrowthScore({
    required List<FragmentDto> fragments,
    required List<RecoveryDto> recoveries,
    required PlatformInt64 nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_fragment_dto(fragments, serializer);
          sse_encode_list_recovery_dto(recoveries, serializer);
          sse_encode_i_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFadeGrowthScoreConstMeta,
        argValues: [fragments, recoveries, nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFadeGrowthScoreConstMeta => const TaskConstMeta(
    debugName: "growth_score",
    argNames: ["fragments", "recoveries", "nowMs"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  RecordRecoveryOutcomeDto crateApiRecoveryRecordRecovery({
    required RecoveryDto recovery,
    required List<FragmentDto> relatedFragments,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_recovery_dto(recovery, serializer);
          sse_encode_list_fragment_dto(relatedFragments, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_recovery_outcome_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRecoveryRecordRecoveryConstMeta,
        argValues: [recovery, relatedFragments],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryRecordRecoveryConstMeta =>
      const TaskConstMeta(
        debugName: "record_recovery",
        argNames: ["recovery", "relatedFragments"],
      );

  @override
  int crateApiDtoSupportedFragmentSchemaVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDtoSupportedFragmentSchemaVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDtoSupportedFragmentSchemaVersionConstMeta =>
      const TaskConstMeta(
        debugName: "supported_fragment_schema_version",
        argNames: [],
      );

  @override
  int crateApiDtoSupportedRecoverySchemaVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDtoSupportedRecoverySchemaVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDtoSupportedRecoverySchemaVersionConstMeta =>
      const TaskConstMeta(
        debugName: "supported_recovery_schema_version",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  FragmentDto dco_decode_box_autoadd_fragment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fragment_dto(raw);
  }

  @protected
  RecoveryDto dco_decode_box_autoadd_recovery_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_recovery_dto(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FragmentDto dco_decode_fragment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FragmentDto(
      schemaVersion: dco_decode_u_32(arr[0]),
      id: dco_decode_String(arr[1]),
      createdAtMs: dco_decode_i_64(arr[2]),
      intensity: dco_decode_u_8(arr[3]),
      fadePeriodDays: dco_decode_u_32(arr[4]),
      stage: dco_decode_String(arr[5]),
    );
  }

  @protected
  FragmentViewDto dco_decode_fragment_view_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FragmentViewDto(
      id: dco_decode_String(arr[0]),
      fadeLevel: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  HomeViewDto dco_decode_home_view_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HomeViewDto(
      schemaVersion: dco_decode_u_32(arr[0]),
      fragments: dco_decode_list_fragment_view_dto(arr[1]),
      growthScore: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FragmentDto> dco_decode_list_fragment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fragment_dto).toList();
  }

  @protected
  List<FragmentViewDto> dco_decode_list_fragment_view_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fragment_view_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RecoveryDto> dco_decode_list_recovery_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_recovery_dto).toList();
  }

  @protected
  RecordRecoveryOutcomeDto dco_decode_record_recovery_outcome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RecordRecoveryOutcomeDto(
      schemaVersion: dco_decode_u_32(arr[0]),
      recovery: dco_decode_recovery_dto(arr[1]),
      fragmentsToAdvance: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  RecoveryDto dco_decode_recovery_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RecoveryDto(
      schemaVersion: dco_decode_u_32(arr[0]),
      id: dco_decode_String(arr[1]),
      createdAtMs: dco_decode_i_64(arr[2]),
      intensity: dco_decode_u_8(arr[3]),
      description: dco_decode_String(arr[4]),
      relatedFragmentIds: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  FragmentDto sse_decode_box_autoadd_fragment_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fragment_dto(deserializer));
  }

  @protected
  RecoveryDto sse_decode_box_autoadd_recovery_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_recovery_dto(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FragmentDto sse_decode_fragment_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schemaVersion = sse_decode_u_32(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    var var_intensity = sse_decode_u_8(deserializer);
    var var_fadePeriodDays = sse_decode_u_32(deserializer);
    var var_stage = sse_decode_String(deserializer);
    return FragmentDto(
      schemaVersion: var_schemaVersion,
      id: var_id,
      createdAtMs: var_createdAtMs,
      intensity: var_intensity,
      fadePeriodDays: var_fadePeriodDays,
      stage: var_stage,
    );
  }

  @protected
  FragmentViewDto sse_decode_fragment_view_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_fadeLevel = sse_decode_f_64(deserializer);
    return FragmentViewDto(id: var_id, fadeLevel: var_fadeLevel);
  }

  @protected
  HomeViewDto sse_decode_home_view_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schemaVersion = sse_decode_u_32(deserializer);
    var var_fragments = sse_decode_list_fragment_view_dto(deserializer);
    var var_growthScore = sse_decode_f_64(deserializer);
    return HomeViewDto(
      schemaVersion: var_schemaVersion,
      fragments: var_fragments,
      growthScore: var_growthScore,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FragmentDto> sse_decode_list_fragment_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FragmentDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fragment_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<FragmentViewDto> sse_decode_list_fragment_view_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FragmentViewDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fragment_view_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RecoveryDto> sse_decode_list_recovery_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RecoveryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recovery_dto(deserializer));
    }
    return ans_;
  }

  @protected
  RecordRecoveryOutcomeDto sse_decode_record_recovery_outcome_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schemaVersion = sse_decode_u_32(deserializer);
    var var_recovery = sse_decode_recovery_dto(deserializer);
    var var_fragmentsToAdvance = sse_decode_list_String(deserializer);
    return RecordRecoveryOutcomeDto(
      schemaVersion: var_schemaVersion,
      recovery: var_recovery,
      fragmentsToAdvance: var_fragmentsToAdvance,
    );
  }

  @protected
  RecoveryDto sse_decode_recovery_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schemaVersion = sse_decode_u_32(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    var var_intensity = sse_decode_u_8(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_relatedFragmentIds = sse_decode_list_String(deserializer);
    return RecoveryDto(
      schemaVersion: var_schemaVersion,
      id: var_id,
      createdAtMs: var_createdAtMs,
      intensity: var_intensity,
      description: var_description,
      relatedFragmentIds: var_relatedFragmentIds,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_fragment_dto(
    FragmentDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fragment_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_recovery_dto(
    RecoveryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_recovery_dto(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fragment_dto(FragmentDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.schemaVersion, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
    sse_encode_u_8(self.intensity, serializer);
    sse_encode_u_32(self.fadePeriodDays, serializer);
    sse_encode_String(self.stage, serializer);
  }

  @protected
  void sse_encode_fragment_view_dto(
    FragmentViewDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_f_64(self.fadeLevel, serializer);
  }

  @protected
  void sse_encode_home_view_dto(HomeViewDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.schemaVersion, serializer);
    sse_encode_list_fragment_view_dto(self.fragments, serializer);
    sse_encode_f_64(self.growthScore, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_fragment_dto(
    List<FragmentDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fragment_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_fragment_view_dto(
    List<FragmentViewDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fragment_view_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_recovery_dto(
    List<RecoveryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recovery_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_record_recovery_outcome_dto(
    RecordRecoveryOutcomeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.schemaVersion, serializer);
    sse_encode_recovery_dto(self.recovery, serializer);
    sse_encode_list_String(self.fragmentsToAdvance, serializer);
  }

  @protected
  void sse_encode_recovery_dto(RecoveryDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.schemaVersion, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
    sse_encode_u_8(self.intensity, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_list_String(self.relatedFragmentIds, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
