// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/dto.dart';
import 'api/fade.dart';
import 'api/recovery.dart';
import 'api/view.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  FragmentDto dco_decode_box_autoadd_fragment_dto(dynamic raw);

  @protected
  RecoveryDto dco_decode_box_autoadd_recovery_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FragmentDto dco_decode_fragment_dto(dynamic raw);

  @protected
  FragmentViewDto dco_decode_fragment_view_dto(dynamic raw);

  @protected
  HomeViewDto dco_decode_home_view_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FragmentDto> dco_decode_list_fragment_dto(dynamic raw);

  @protected
  List<FragmentViewDto> dco_decode_list_fragment_view_dto(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecoveryDto> dco_decode_list_recovery_dto(dynamic raw);

  @protected
  RecordRecoveryOutcomeDto dco_decode_record_recovery_outcome_dto(dynamic raw);

  @protected
  RecoveryDto dco_decode_recovery_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  FragmentDto sse_decode_box_autoadd_fragment_dto(SseDeserializer deserializer);

  @protected
  RecoveryDto sse_decode_box_autoadd_recovery_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FragmentDto sse_decode_fragment_dto(SseDeserializer deserializer);

  @protected
  FragmentViewDto sse_decode_fragment_view_dto(SseDeserializer deserializer);

  @protected
  HomeViewDto sse_decode_home_view_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FragmentDto> sse_decode_list_fragment_dto(SseDeserializer deserializer);

  @protected
  List<FragmentViewDto> sse_decode_list_fragment_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecoveryDto> sse_decode_list_recovery_dto(SseDeserializer deserializer);

  @protected
  RecordRecoveryOutcomeDto sse_decode_record_recovery_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecoveryDto sse_decode_recovery_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fragment_dto(
    FragmentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_recovery_dto(
    RecoveryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fragment_dto(FragmentDto self, SseSerializer serializer);

  @protected
  void sse_encode_fragment_view_dto(
    FragmentViewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_view_dto(HomeViewDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fragment_dto(
    List<FragmentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fragment_view_dto(
    List<FragmentViewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recovery_dto(
    List<RecoveryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_recovery_outcome_dto(
    RecordRecoveryOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_dto(RecoveryDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
