// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StorageErrorCode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `conflict`, `corrupted`, `internal`, `invalid_argument`, `not_found`, `now_ms`, `quota_exceeded`, `sha256_hex`

/// 跨边界的标准化存储错误。Dart 侧据 `code` 字段映射 UI 文案 / 重试策略。
///
/// `code` 取值范围见 [`StorageErrorCode`]。任何 Rust 内部错误 (含 `io::Error` /
/// `sled::Error` / `serde_json::Error`) 在抵达 FFI 边界前都应转成此结构,
/// 不暴露内部类型字符串。
class StorageError implements FrbException {
  final String code;
  final String message;

  const StorageError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

/// 通用回执: 内容寻址 / sha256 校验场景的统一返回 (模式 C/J 共用)。
class StorageSampleBlobReceiptDto {
  /// 写入后 / 校验后的资源 ID (一般是 hex sha256 前缀)。
  final String id;

  /// 总字节数。
  final BigInt sizeBytes;

  /// 内容 sha256 (64 hex)。
  final String sha256Hex;

  const StorageSampleBlobReceiptDto({
    required this.id,
    required this.sizeBytes,
    required this.sha256Hex,
  });

  @override
  int get hashCode => id.hashCode ^ sizeBytes.hashCode ^ sha256Hex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSampleBlobReceiptDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sizeBytes == other.sizeBytes &&
          sha256Hex == other.sha256Hex;
}
