// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_sled_err`, `now_ms`, `open_db`, `pack`, `pool`, `unpack`

Future<void> storageSamplePcachePut({
  required String path,
  required List<int> key,
  required List<int> value,
  required BigInt ttlMs,
}) => RustLib.instance.api
    .crateApiStoragePatternHPersistentCacheStorageSamplePcachePut(
      path: path,
      key: key,
      value: value,
      ttlMs: ttlMs,
    );

Future<Uint8List?> storageSamplePcacheGet({
  required String path,
  required List<int> key,
}) => RustLib.instance.api
    .crateApiStoragePatternHPersistentCacheStorageSamplePcacheGet(
      path: path,
      key: key,
    );

Future<bool> storageSamplePcacheDelete({
  required String path,
  required List<int> key,
}) => RustLib.instance.api
    .crateApiStoragePatternHPersistentCacheStorageSamplePcacheDelete(
      path: path,
      key: key,
    );

/// 遍历清除所有已过期条目。
Future<BigInt> storageSamplePcacheGcExpired({required String path}) => RustLib
    .instance
    .api
    .crateApiStoragePatternHPersistentCacheStorageSamplePcacheGcExpired(
      path: path,
    );
