// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_sled_err`, `open_db`, `pool`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> storageSampleKvPut({
  required String path,
  required List<int> key,
  required List<int> value,
}) => RustLib.instance.api.crateApiStoragePatternFOrderedKvStorageSampleKvPut(
  path: path,
  key: key,
  value: value,
);

Future<Uint8List?> storageSampleKvGet({
  required String path,
  required List<int> key,
}) => RustLib.instance.api.crateApiStoragePatternFOrderedKvStorageSampleKvGet(
  path: path,
  key: key,
);

Future<bool> storageSampleKvDelete({
  required String path,
  required List<int> key,
}) =>
    RustLib.instance.api.crateApiStoragePatternFOrderedKvStorageSampleKvDelete(
      path: path,
      key: key,
    );

/// 按前缀扫描; `limit=0` 表示不限。
Future<List<StorageSampleKvEntryDto>> storageSampleKvScanPrefix({
  required String path,
  required List<int> prefix,
  required BigInt limit,
}) => RustLib.instance.api
    .crateApiStoragePatternFOrderedKvStorageSampleKvScanPrefix(
      path: path,
      prefix: prefix,
      limit: limit,
    );

/// 范围查询 `[from, to)`; `limit=0` 表示不限。
Future<List<StorageSampleKvEntryDto>> storageSampleKvRange({
  required String path,
  required List<int> from,
  required List<int> to,
  required BigInt limit,
}) => RustLib.instance.api.crateApiStoragePatternFOrderedKvStorageSampleKvRange(
  path: path,
  from: from,
  to: to,
  limit: limit,
);

Future<BigInt> storageSampleKvFlush({required String path}) => RustLib
    .instance
    .api
    .crateApiStoragePatternFOrderedKvStorageSampleKvFlush(path: path);

class StorageSampleKvEntryDto {
  final Uint8List key;
  final Uint8List value;

  const StorageSampleKvEntryDto({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSampleKvEntryDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}
