// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `evict_if_needed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Entry`, `Inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 工厂入口: Dart 侧 `await storageSampleOpenMemoryCache(...)`。
Future<StorageSampleMemoryCache> storageSampleOpenMemoryCache({
  required BigInt capacity,
  BigInt? defaultTtlMs,
}) => RustLib.instance.api
    .crateApiStoragePatternAMemoryStorageSampleOpenMemoryCache(
      capacity: capacity,
      defaultTtlMs: defaultTtlMs,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StorageSampleMemoryCache>>
abstract class StorageSampleMemoryCache implements RustOpaqueInterface {
  Future<void> clear();

  Future<bool> delete({required String key});

  /// 删除所有已过期条目, 返回删除数量。
  Future<BigInt> gcExpired();

  /// 读取; 命中返回 `Some(value)` 并更新 LRU 序号。已过期视为 miss 并删除。
  Future<Uint8List?> get_({required String key});

  /// 工厂: `capacity=0` 时使用默认值 1024。
  static Future<StorageSampleMemoryCache> open({
    required BigInt capacity,
    BigInt? defaultTtlMs,
  }) => RustLib.instance.api
      .crateApiStoragePatternAMemoryStorageSampleMemoryCacheOpen(
        capacity: capacity,
        defaultTtlMs: defaultTtlMs,
      );

  /// 写入; 若超出 capacity, 淘汰最旧条目。`ttl_ms=None` 用默认 TTL。
  Future<void> put({
    required String key,
    required List<int> value,
    BigInt? ttlMs,
  });

  Future<StorageSampleCacheStatsDto> stats();
}

class StorageSampleCacheStatsDto {
  final BigInt len;
  final BigInt capacity;
  final BigInt hits;
  final BigInt misses;

  const StorageSampleCacheStatsDto({
    required this.len,
    required this.capacity,
    required this.hits,
    required this.misses,
  });

  @override
  int get hashCode =>
      len.hashCode ^ capacity.hashCode ^ hits.hashCode ^ misses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSampleCacheStatsDto &&
          runtimeType == other.runtimeType &&
          len == other.len &&
          capacity == other.capacity &&
          hits == other.hits &&
          misses == other.misses;
}
