// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fsync_dir`, `tmp_path`, `validate_target`

/// 原子写。`fsync=true` (推荐) 时保证断电后只可能看到旧值或新值, 不会半写。
Future<BigInt> storageSampleAtomicWrite({
  required String path,
  required List<int> bytes,
  required bool fsync,
}) => RustLib.instance.api
    .crateApiStoragePatternBAtomicFileStorageSampleAtomicWrite(
      path: path,
      bytes: bytes,
      fsync: fsync,
    );

/// 读取整个文件; 文件不存在返回 `not_found`。
Future<Uint8List> storageSampleAtomicRead({required String path}) => RustLib
    .instance
    .api
    .crateApiStoragePatternBAtomicFileStorageSampleAtomicRead(path: path);

/// 仅当目标不存在时写入; 用于 first-time init。
Future<bool> storageSampleAtomicWriteIfAbsent({
  required String path,
  required List<int> bytes,
  required bool fsync,
}) => RustLib.instance.api
    .crateApiStoragePatternBAtomicFileStorageSampleAtomicWriteIfAbsent(
      path: path,
      bytes: bytes,
      fsync: fsync,
    );
