// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_files`, `extract_number`, `extract_string`, `json_string`, `now_ms`, `parse_body_item`, `parse_manifest`, `validate_rel_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BodyItem`, `Manifest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 把 `src_dir` 下所有文件 (递归) 备份到 `dest_archive`。
Future<StorageSampleBackupReceiptDto> storageSampleBackupExport({
  required String srcDir,
  required String destArchive,
}) =>
    RustLib.instance.api.crateApiStoragePatternJBackupStorageSampleBackupExport(
      srcDir: srcDir,
      destArchive: destArchive,
    );

/// 从 archive 还原到 `dest_dir`。`overwrite=false` 时若目标文件存在则返回 `conflict`。
Future<StorageSampleBackupReceiptDto> storageSampleBackupImport({
  required String archive,
  required String destDir,
  required bool overwrite,
}) =>
    RustLib.instance.api.crateApiStoragePatternJBackupStorageSampleBackupImport(
      archive: archive,
      destDir: destDir,
      overwrite: overwrite,
    );

class StorageSampleBackupReceiptDto {
  final String archivePath;
  final BigInt fileCount;
  final BigInt totalBytes;
  final String archiveSha256;

  const StorageSampleBackupReceiptDto({
    required this.archivePath,
    required this.fileCount,
    required this.totalBytes,
    required this.archiveSha256,
  });

  @override
  int get hashCode =>
      archivePath.hashCode ^
      fileCount.hashCode ^
      totalBytes.hashCode ^
      archiveSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSampleBackupReceiptDto &&
          runtimeType == other.runtimeType &&
          archivePath == other.archivePath &&
          fileCount == other.fileCount &&
          totalBytes == other.totalBytes &&
          archiveSha256 == other.archiveSha256;
}
