// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `copy_dir_recursive`, `parse_id`, `scan_dir`, `validate_label`, `validate_rel_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 创建一个新快照。返回 snapshot id (目录名)。
Future<StorageSampleSnapshotDto> storageSampleSnapshotTake({
  required String root,
  required String label,
  required List<StorageSampleSnapshotFile> files,
}) => RustLib.instance.api
    .crateApiStoragePatternDSnapshotStorageSampleSnapshotTake(
      root: root,
      label: label,
      files: files,
    );

/// 列出所有快照, 按时间升序。
Future<List<StorageSampleSnapshotDto>> storageSampleSnapshotList({
  required String root,
}) => RustLib.instance.api
    .crateApiStoragePatternDSnapshotStorageSampleSnapshotList(root: root);

/// 把指定快照的文件还原到 `dest_dir` (会先清空 dest 同名文件)。
Future<BigInt> storageSampleSnapshotRestore({
  required String root,
  required String id,
  required String destDir,
}) => RustLib.instance.api
    .crateApiStoragePatternDSnapshotStorageSampleSnapshotRestore(
      root: root,
      id: id,
      destDir: destDir,
    );

/// 仅保留最近 `keep` 个快照, 其余删除。返回删除数量。
Future<BigInt> storageSampleSnapshotPrune({
  required String root,
  required int keep,
}) => RustLib.instance.api
    .crateApiStoragePatternDSnapshotStorageSampleSnapshotPrune(
      root: root,
      keep: keep,
    );

class StorageSampleSnapshotDto {
  final String id;
  final BigInt tsMs;
  final String label;
  final BigInt fileCount;
  final BigInt totalBytes;

  const StorageSampleSnapshotDto({
    required this.id,
    required this.tsMs,
    required this.label,
    required this.fileCount,
    required this.totalBytes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tsMs.hashCode ^
      label.hashCode ^
      fileCount.hashCode ^
      totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSampleSnapshotDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tsMs == other.tsMs &&
          label == other.label &&
          fileCount == other.fileCount &&
          totalBytes == other.totalBytes;
}

class StorageSampleSnapshotFile {
  /// 相对快照根的路径, e.g. "config.json" 或 "subdir/data.bin"。
  final String relPath;
  final Uint8List bytes;

  const StorageSampleSnapshotFile({required this.relPath, required this.bytes});

  @override
  int get hashCode => relPath.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSampleSnapshotFile &&
          runtimeType == other.runtimeType &&
          relPath == other.relPath &&
          bytes == other.bytes;
}
