// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 加密: 返回 `[nonce(12) || ciphertext_with_tag]`。
Future<Uint8List> storageSampleEnvelopeEncrypt({
  required List<int> key,
  required List<int> plaintext,
  required List<int> aad,
}) => RustLib.instance.api
    .crateApiStoragePatternIEncryptionStorageSampleEnvelopeEncrypt(
      key: key,
      plaintext: plaintext,
      aad: aad,
    );

/// 解密; 数据被改 / key 错 / AAD 错 → `corrupted`。
Future<Uint8List> storageSampleEnvelopeDecrypt({
  required List<int> key,
  required List<int> envelope,
  required List<int> aad,
}) => RustLib.instance.api
    .crateApiStoragePatternIEncryptionStorageSampleEnvelopeDecrypt(
      key: key,
      envelope: envelope,
      aad: aad,
    );

/// 工具: 生成新的 32 字节随机数据密钥 (CSPRNG)。
Future<Uint8List> storageSampleGenerateDataKey() => RustLib.instance.api
    .crateApiStoragePatternIEncryptionStorageSampleGenerateDataKey();
