// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blob_path`, `validate_id`

/// 写入 blob; 若已存在则跳过 (内容相同, 内容寻址保证)。
Future<StorageSampleBlobReceiptDto> storageSampleBlobPut({
  required String root,
  required List<int> content,
}) => RustLib.instance.api.crateApiStoragePatternCBlobStorageSampleBlobPut(
  root: root,
  content: content,
);

/// 读取并自动校验 sha256; 不一致返回 `corrupted`。
Future<Uint8List> storageSampleBlobGet({
  required String root,
  required String id,
}) => RustLib.instance.api.crateApiStoragePatternCBlobStorageSampleBlobGet(
  root: root,
  id: id,
);

Future<bool> storageSampleBlobExists({
  required String root,
  required String id,
}) => RustLib.instance.api.crateApiStoragePatternCBlobStorageSampleBlobExists(
  root: root,
  id: id,
);

Future<bool> storageSampleBlobDelete({
  required String root,
  required String id,
}) => RustLib.instance.api.crateApiStoragePatternCBlobStorageSampleBlobDelete(
  root: root,
  id: id,
);
