// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_number`, `extract_raw_after`, `extract_string`, `json_string`, `parse_event`, `validate_event`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 追加一条事件。文件不存在则创建。
Future<void> storageSampleEventLogAppend({
  required String path,
  required StorageSampleEventDto event,
}) => RustLib.instance.api
    .crateApiStoragePatternEEventLogStorageSampleEventLogAppend(
      path: path,
      event: event,
    );

/// 从 `from_seq` 起读所有事件 (inclusive)。文件不存在视为空。
/// 注意: 返回前会全部加载到内存; 大日志请用 `replay_from_with_limit`。
Future<List<StorageSampleEventDto>> storageSampleEventLogReplayFrom({
  required String path,
  required BigInt fromSeq,
}) => RustLib.instance.api
    .crateApiStoragePatternEEventLogStorageSampleEventLogReplayFrom(
      path: path,
      fromSeq: fromSeq,
    );

/// 带上限版本。`limit=0` 表示不限。
Future<List<StorageSampleEventDto>> storageSampleEventLogReplayFromWithLimit({
  required String path,
  required BigInt fromSeq,
  required BigInt limit,
}) => RustLib.instance.api
    .crateApiStoragePatternEEventLogStorageSampleEventLogReplayFromWithLimit(
      path: path,
      fromSeq: fromSeq,
      limit: limit,
    );

/// 截断日志, 保留 `seq <= keep_until` 的事件。实现为 read → filter → atomic write。
Future<BigInt> storageSampleEventLogTruncateTo({
  required String path,
  required BigInt keepUntil,
}) => RustLib.instance.api
    .crateApiStoragePatternEEventLogStorageSampleEventLogTruncateTo(
      path: path,
      keepUntil: keepUntil,
    );

class StorageSampleEventDto {
  final BigInt seq;
  final BigInt tsMs;
  final String kind;
  final String aggregateId;

  /// 原样存储, 由消费方解析。要求单行 (不含 '\n')。
  final String payloadJson;

  const StorageSampleEventDto({
    required this.seq,
    required this.tsMs,
    required this.kind,
    required this.aggregateId,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      seq.hashCode ^
      tsMs.hashCode ^
      kind.hashCode ^
      aggregateId.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSampleEventDto &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          tsMs == other.tsMs &&
          kind == other.kind &&
          aggregateId == other.aggregateId &&
          payloadJson == other.payloadJson;
}
