// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_sled_err`, `open_db`, `pool`, `validate_key`

Future<void> storageSampleSettingsSet({
  required String path,
  required String key,
  required String value,
}) => RustLib.instance.api
    .crateApiStoragePatternGSettingsStorageSampleSettingsSet(
      path: path,
      key: key,
      value: value,
    );

Future<String?> storageSampleSettingsGet({
  required String path,
  required String key,
}) => RustLib.instance.api
    .crateApiStoragePatternGSettingsStorageSampleSettingsGet(
      path: path,
      key: key,
    );

Future<bool> storageSampleSettingsDelete({
  required String path,
  required String key,
}) => RustLib.instance.api
    .crateApiStoragePatternGSettingsStorageSampleSettingsDelete(
      path: path,
      key: key,
    );

/// 一次读完所有 settings (启动期典型用法)。
Future<List<(String, String)>> storageSampleSettingsDump({
  required String path,
}) => RustLib.instance.api
    .crateApiStoragePatternGSettingsStorageSampleSettingsDump(path: path);
