// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `into_domain`, `into_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// 公开给 Dart 用于运行时校验：当前 Rust 端支持的 DTO 版本。
int supportedFragmentSchemaVersion() =>
    RustLib.instance.api.crateApiDtoSupportedFragmentSchemaVersion();

int supportedRecoverySchemaVersion() =>
    RustLib.instance.api.crateApiDtoSupportedRecoverySchemaVersion();

class FragmentDto {
  final int schemaVersion;
  final String id;
  final PlatformInt64 createdAtMs;
  final int intensity;
  final int fadePeriodDays;

  /// `outburst` | `recovery` | `relapse`
  final String stage;

  const FragmentDto({
    required this.schemaVersion,
    required this.id,
    required this.createdAtMs,
    required this.intensity,
    required this.fadePeriodDays,
    required this.stage,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      id.hashCode ^
      createdAtMs.hashCode ^
      intensity.hashCode ^
      fadePeriodDays.hashCode ^
      stage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FragmentDto &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          id == other.id &&
          createdAtMs == other.createdAtMs &&
          intensity == other.intensity &&
          fadePeriodDays == other.fadePeriodDays &&
          stage == other.stage;
}

class FragmentViewDto {
  final String id;
  final double fadeLevel;

  const FragmentViewDto({required this.id, required this.fadeLevel});

  @override
  int get hashCode => id.hashCode ^ fadeLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FragmentViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fadeLevel == other.fadeLevel;
}

class HomeViewDto {
  final int schemaVersion;
  final List<FragmentViewDto> fragments;
  final double growthScore;

  const HomeViewDto({
    required this.schemaVersion,
    required this.fragments,
    required this.growthScore,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^ fragments.hashCode ^ growthScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeViewDto &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          fragments == other.fragments &&
          growthScore == other.growthScore;
}

class RecordRecoveryOutcomeDto {
  final int schemaVersion;
  final RecoveryDto recovery;
  final List<String> fragmentsToAdvance;

  const RecordRecoveryOutcomeDto({
    required this.schemaVersion,
    required this.recovery,
    required this.fragmentsToAdvance,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^ recovery.hashCode ^ fragmentsToAdvance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordRecoveryOutcomeDto &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          recovery == other.recovery &&
          fragmentsToAdvance == other.fragmentsToAdvance;
}

class RecoveryDto {
  final int schemaVersion;
  final String id;
  final PlatformInt64 createdAtMs;
  final int intensity;
  final String description;
  final List<String> relatedFragmentIds;

  const RecoveryDto({
    required this.schemaVersion,
    required this.id,
    required this.createdAtMs,
    required this.intensity,
    required this.description,
    required this.relatedFragmentIds,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      id.hashCode ^
      createdAtMs.hashCode ^
      intensity.hashCode ^
      description.hashCode ^
      relatedFragmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveryDto &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          id == other.id &&
          createdAtMs == other.createdAtMs &&
          intensity == other.intensity &&
          description == other.description &&
          relatedFragmentIds == other.relatedFragmentIds;
}
