// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

double fadeLevel({
  required FragmentDto fragment,
  required List<RecoveryDto> recoveries,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiFadeFadeLevel(
  fragment: fragment,
  recoveries: recoveries,
  nowMs: nowMs,
);

double growthScore({
  required List<FragmentDto> fragments,
  required List<RecoveryDto> recoveries,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiFadeGrowthScore(
  fragments: fragments,
  recoveries: recoveries,
  nowMs: nowMs,
);

/// 提供给 UI 成长曲线使用的批量采样接口。
///
/// 返回 `samples + 1` 个点，代替 Dart 侧重复实现同一算法。
Float64List growthScoreSeries({
  required List<FragmentDto> fragments,
  required List<RecoveryDto> recoveries,
  required PlatformInt64 startMs,
  required PlatformInt64 endMs,
  required int samples,
}) => RustLib.instance.api.crateApiFadeGrowthScoreSeries(
  fragments: fragments,
  recoveries: recoveries,
  startMs: startMs,
  endMs: endMs,
  samples: samples,
);
