// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

double fadeLevel({
  required FragmentDto fragment,
  required List<RecoveryDto> recoveries,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiFadeFadeLevel(
  fragment: fragment,
  recoveries: recoveries,
  nowMs: nowMs,
);

double growthScore({
  required List<FragmentDto> fragments,
  required List<RecoveryDto> recoveries,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiFadeGrowthScore(
  fragments: fragments,
  recoveries: recoveries,
  nowMs: nowMs,
);
